spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/db_name
    driver-class-name: org.postgresql.Driver
    username: postgres_user
    password: password
  flyway:
    user: postgres_user
    password: password
    url: jdbc:postgresql://localhost:8080/db_name
    locations: db.migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect